[build]
  command = "pip install -r requirements.txt"
  publish = "static"

[functions]
  included_files = ["templates/**", "static/**", "dataset.csv", "rides.csv", "krr_engine.py", "app.py"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
